import { ComparisonResult } from './types';

export const SAMPLE_COMPARISON: ComparisonResult = {
  docAName: 'Initial Offer / Contract Version A (Draft)',
  docBName: 'Final Counter-Agreement / Version B (Revised)',
  executiveComparison: 'Comparison between Version A and Version B reveals 4 major contractual modifications. Version B provides a 50% salary increase (₹50,000 to ₹75,000/mo) and mutualizes termination rights, but introduces aggressive defensive covenants: the notice period is tripled from 30 to 90 days, and a new 12-month post-employment non-compete restriction has been added.',
  summaryOfDeltas: {
    added: 2,
    removed: 0,
    modified: 3,
    highRiskChanges: 2,
  },
  keyFindings: [
    'Notice period tripled from 30 days to 90 days (⚠ Major lock-in risk)',
    '12-month post-employment Non-Compete restriction introduced (⚠ High risk addition)',
    'Compensation increased from ₹50,000 to ₹75,000 per month (✓ Favorable)',
    'Termination rights changed from Employer-only to Mutual 90-day notice (✓ Favorable)',
    'Training cost clawback threshold reduced from 24 months to 12 months (✓ Favorable)',
  ],
  clauses: [
    {
      clauseTitle: 'Notice Period',
      sectionA: 'Section 7.1',
      contentA: 'Either party may terminate employment by giving thirty (30) days prior written notice or basic salary in lieu thereof.',
      sectionB: 'Section 8.2',
      contentB: 'Either party may terminate employment by providing ninety (90) days prior written notice. Employee notice buyout shall be permitted solely at Employer discretion.',
      changeType: 'modified',
      impactAssessment: 'Notice requirement has tripled from 1 month to 3 months, and employer has removed the employee automatic right to buy out the notice period.',
      riskDelta: 'high_risk',
      adviceForUser: 'Negotiate back to 45 or 60 days. In the tech industry, 90 days can cause prospective employers to retract future job offers.',
    },
    {
      clauseTitle: 'Non-Compete Restriction',
      sectionA: 'Not Present (Omitted)',
      contentA: 'No restrictive covenant on subsequent post-employment engagements.',
      sectionB: 'Section 6.1 (New Clause)',
      contentB: 'For a period of twelve (12) months following termination, Employee shall not directly or indirectly work for or consult with any enterprise operating in the same domain across India.',
      changeType: 'added',
      impactAssessment: 'Brand new restrictive covenant that did not exist in Version A. Restricts your right to switch to competitor firms.',
      riskDelta: 'high_risk',
      adviceForUser: 'Highlight Section 27 of the Indian Contract Act (voidness of post-employment restraints) and request deletion or restriction strictly to customer poaching.',
    },
    {
      clauseTitle: 'Monthly Compensation',
      sectionA: 'Section 2.1',
      contentA: 'Gross Monthly Remuneration shall be INR 50,000/- (Rupees Fifty Thousand Only).',
      sectionB: 'Section 2.1',
      contentB: 'Gross Monthly Remuneration shall be INR 75,000/- (Rupees Seventy-Five Thousand Only).',
      changeType: 'modified',
      impactAssessment: 'Positive 50% salary increment achieved in revised draft.',
      riskDelta: 'favorable_to_user',
      adviceForUser: 'Verify the split between Fixed Base Pay and Variable/Performance bonus to confirm real in-hand cashflow.',
    },
    {
      clauseTitle: 'Termination Rights',
      sectionA: 'Section 7.0',
      contentA: 'Company reserves the right to terminate at will with 15 days notice. Employee cannot terminate before 1 year.',
      sectionB: 'Section 8.1',
      contentB: 'Both Employer and Employee maintain equal mutual rights to terminate the engagement upon notice.',
      changeType: 'modified',
      impactAssessment: 'Unilateral employer lock-in removed in favor of mutual termination rights.',
      riskDelta: 'favorable_to_user',
      adviceForUser: 'Ensure the definition of "Immediate Cause" remains balanced and objective.',
    },
    {
      clauseTitle: 'Training Bond & Liquidated Damages',
      sectionA: 'Section 9.2',
      contentA: 'Employee must pay INR 2,00,000 if departing within 24 months of joining date.',
      sectionB: 'Section 9.2',
      contentB: 'Employee shall reimburse actual certified external course costs up to INR 75,000 if departing within 12 months.',
      changeType: 'modified',
      impactAssessment: 'Bond period cut from 2 years to 1 year, and max penalty reduced by over 60% with proof-of-cost requirement.',
      riskDelta: 'favorable_to_user',
      adviceForUser: 'Confirm what courses count and request written receipts before any payroll deduction is authorized.',
    },
  ],
  negotiationRecommendations: [
    'Counter the 90-day notice period in Section 8.2: propose 45 days, or 60 days with guaranteed mutual buyout.',
    'Ask for the newly added Section 6.1 (Non-Compete) to be dropped in light of Section 27 of the Indian Contract Act.',
    'Accept the revised ₹75,000 compensation and mutual termination rights.',
    'Request that the liquidated damages in Section 9.2 only trigger if the company paid for accredited third-party certification.',
  ],
};
